name: Meson CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: macOS Debug build
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Meson
        run: |
          python -m pip install --upgrade pip setuptools
          pip install meson

      - name: Install dependencies
        run: |
          brew install cmake ninja pkg-config libass boost zlib ffms2 fftw hunspell luarocks pulseaudio ffmpeg boost wxwidgets icu4c luajit
          export LDFLAGS="-L/opt/homebrew/Cellar/icu4c/lib"
          export CPPFLAGS="-I//opt/homebrew/Cellar/icu4c/include"
          export PKG_CONFIG_PATH="/opt/homebrew/Cellar/cu4c/lib/pkgconfig"

      - name: Configure
        run: meson build_static -Ddefault_library=static -Dbuildtype=debugoptimized -Dbuild_osx_bundle=true -Dlocal_boost=true

      - name: Build
        run: meson compile -C build_static

      - name: Run test
        run: meson test -C build_static --verbose
        if: false

      - name: Generate macOS installer
        run: |
          meson compile osx-bundle -C build_static
          codesign --sign - --force --deep build_static/Aegisub.app
          meson compile osx-build-dmg -C build_static

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Aegisub-darwin-aarch64
          path: |
            build_static/Aegisub-*.dmg
            build_static/Aegisub.app
          if-no-files-found: error
